export default [
  {
    rating: 5,
    img: "/Image/facepowder.jpg",
    title: "SD Facepowder",
    price: 41.0,
    sales: false,
  },
  {
    rating: 4,
    img: "/Image/facepowderkit.jpg",
    title: "SD Milk facepowder ",
    price: 48.0,
    sales: true,
  },
  {
    rating: 4,
    img: "/Image/blush2.jpg",
    title: "SD Blush Powder",
    price: 42.0,
    sales: false,
  },
  {
    rating: 3,
    img: "/Image/purfume1.jpg",
    title: "SD Perfum ",
    price: 85.0,
    sales: true,
  },
  {
    rating: 5,
    img: "/Image/brushkit.jpg",
    title: "SD Brush Kit",
    price: 60.0,
    sales: true,
  },

  {
    rating: 4,
    img: "/Image/eyeshadow1.jpg",
    title: "SD Mate Eye Shadow",
    price: 39.0,
    sales: false,
  },
  {
    rating: 5,
    img: "/Image/eyeshadow2.jpg",
    title: "SD Mate Eye Shadow",
    price: 10.0,
    sales: false,
  },
  {
    rating: 3,
    img: "/Image/lip-pencle.jpg",
    title: "SD Lip Pencle",
    price: 40.0,
    sales: true,
  },
  {
    rating: 5,
    img: "/Image/lipsctick1.jpg",
    title: "SD Nude Shade LipStick",
    price: 64.0,
    sales: true,
  },
  {
    rating: 4,
    img: "/Image/pinklipsctick.jpg",
    title: "SD Mate Hot Pink LipStick",
    price: 50.0,
    sales: true,
  },
  {
    rating: 4,
    img: "/Image/spoung2.jpg",
    title: "SD Coloured Base ",
    price: 29.0,
    sales: false,
  },
  {
    rating: 3,
    img: "/Image/spoung1.jpg",
    title: "SD Base",
    price: 20.0,
    sales: false,
  },
];
