import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navrbar from "./components/Navbar";
import Footer from "./components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Diya Cosmetics",
  description: "Generated by Saadia Saleem",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navrbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
